### ISSUE TITLE
Error when make the critter

### ISSUE THREAD

**Issue by sheldon-pan** [huttered40/critter#61]
centos7.4
g++ 4.8.2
when I make the critter, I get an ERROR
```
src/record/record.cxx:341:200:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for ca?𻰨critter::internal::record(std::ostream&)::__lambda4) (std::pair<stic_string<char>, std::array<double, 6ul> >&, const std::pair<std::basing<char>, std::array<double, 6ul> >&)?
    while (__comp(*__first, __pivot))
```
I don't know if it's because 4.8.5 doesn't fully support c++11.

**Comment by sheldon-pan** [comment]
I changed a new environment with g++5 and openmpi4，
but I don't get the .so file, and only have a "libcritter.a" file in the ./lib.
Does the critter support shared library now?

**Comment by huttered40** [comment]
This project is still in a development phase. The README is no longer reflective of this library and will be updated soon. Shared library support will be added soon as well. I will reply back when these items are complete.

**Comment by sheldon-pan** [comment]
Thanks, I will try the .a file.
By the way,is the first Error  caused  by gcc-4.8.2?
